{% set name = "hpack" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/python-hyper/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d8e1a265716dab0af17672e5f9aef4ce91bf5901f25fad021b49e89fa2541ce3

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=82
    - wheel >=0.46.3,<1
  run:
    - python

test:
  imports:
    - hpack
  source_files:
    - tests
  requires:
    - python
    - pip
    - pytest >=9.0.3,<10
    - hypothesis >=6.152.1,<7
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://python-hyper.org/projects/hpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HTTP/2 Header Encoding for Python
  description: |
    hpack provides a simple Python interface to the HPACK compression algorithm, 
    used to compress HTTP headers in HTTP/2. Used by some of the most popular
    HTTP/2 implementations in Python, HPACK offers a great Python interface as
    well as optional upgrade to optimised C-based compression routines from
    nghttp2.
  dev_url: https://github.com/python-hyper/hpack
  doc_url: https://python-hyper.org/projects/hpack

extra:
  recipe-maintainers:
    - primozgodec
    - astaric
