travis:
  secure:
    BINSTAR_TOKEN: O9f2pIXQhomEvG1/oX17wOO/WZfPD6YE0oLidBGOsSKWa8GdCYZAMWiE1xfS52FVMUu+MC0Otv6ujrFn0dNJtPkUonu8Rsu3oN74BuLiNY2ODhcGZrrGcPalrvbC709mit25/7xXZpVfXLXO0EsRvMcv5b3Ec/aPYiQwFJ0+Afjr4NdKx/ouwEmH3mVKzuAy6jj1951ZpSyVEIKjAdEEw6lc1ohptWgNw2iNSee6gMQqp0ZqZgZ+pHElefsMJ5ZqF3Lw9QsFL8WCHzyI0jTVig/LFZFWACYVfPKjr+uSvCx59Hsp6mPhqa/L3TblHytiI62YQ6ZOHPUtro86hXGAXJfSQI470D4zhgAARLKvNgpZY4qljuQPoBoLrLn3BOlQrDPgAq6nwApbhiem8iq8PbZ/dvc8w16kNVHcR0ynXA9JP0fTpbJh1uQ6QFljHGGHiM9XgCknOVpV37LDGk5M0Hazl1rIT1lIsV5OQFxyP3SCK1UeImoHpSJfvF5+50A5rOeeMRbUiAvx2mNaW8w3V0qXv0JbIgHuqV9bpks09OJ2xYhUo1mwS4rVkFiZ+FgSavpOIpcMPGdZdCtC+yuecNJPM+jrZ/sbLoXBgPxAg/v9pdAlf7xJuHDS5gqjfg3pATaos07Af6RGP/bCWKdpkIuDVQaFzpKFw4VWqqaZTAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
