travis:
  secure:
    BINSTAR_TOKEN: W7t8K8efh+SE3OlL5+YJ9UUSSr4jqgnoqaWwzfpGdUPrCDtqMoV9QfyUFSBte0q6K5xTli4L11PNIXpzrotEq2EuKV3Ooyyl7qRJBIUUgAxObqj26MNokOhapJPT2UIFbTkKtlVnD2aZnow6lRlXV1EE/Psxjs/FEWoNbP8Y9eG4eFuU5u9ev+ZPrT1YrJJL84Rrmg1eGt0Q2chkfXKA+0bKS9nzZNvbGSIYheWGzmZGtLtJz6zv1vvSQ/wMBfAX/YyPpbB2/fB+g7wlpiBVJU8ITvVcV9K37qiVbbbtdnZ30xLhORVW4+KGKf8X3fMkA9/m6fUfjwERPd1XXycRMBSWaEkAsoc7Kal6CAnEwrf2z3i0lfelc5b+HWWa/Dl5CxZXrhgCgEtK8bTLvjmsBjIZOZQF0RdWo8xa8AKxlX8XI+sa3dG3M7dswoy7NgI1alRkcyx7ciQcb+U+quoeU+3wLasTuxUHEJvoQDXUA5N/tju51/HA5dIkcY1UFdDKtQ3BIrLRO4dS2BzeopKL4eMlpYUtqIPk6UHSbh+a/4tTIUL8mERDz5c5XphFKQ9MZN6ZQu9M2AnH6JRijzIzu592NNxiK4Xr3M07NeV+Ux3LwZOckgjRXe797nPuSdwaa2IO2vX92rcMH31Cg6osGGmbBIg4z7Rqw40CqAqaOKs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
